# Site settings
title: Pollock
email: david.pollock@ucdenver.edu
url: http://pollocklaboratory.github.io/
description: "Protein sequence, structure, and functional evolution; Evolutionary genomics; Adaptive coevolution and ancestral reconstruction; Evolution of mitochondrial genomes; Evolutionary theory; Testing evolutionary predictions through mutagenesis and directed evolution."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: The Pollock Laboratory

about:
  - title: publications
    icon: book
    url: http://github.com/PollockLaboratory/Publications
  - title: courses
    icon: university
    url: http://github.com/PollockLaboratory/Courses

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    icon: github
    url: http://github.com/PollockLaboratory
  - title: email
    icon: envelope
    url: mailto:david.pollock@CUAnschutz.edu

# Build settings
markdown: kramdown
permalink: pretty
